[package]
name = "dinotree"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]


[dependencies]
ordered-float = "0.5.0"
rayon = "0.9.*"
pdqselect = "0.1.0"
odds = "0.2.25"  #used for Vec::retain_mut
rand = "0.3"
compt = {path="../compt"}
#axgeom = "0.1.0"
axgeom = {path="../axgeom"}
smallvec = "0.6.0"