[package]
name = "dinotree_alg"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]


[dev-dependencies]
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
num = "0.1.42"
piston_window = "*"

[dependencies]
is_sorted = "0.1.0"
rayon = "1.0.2"
#compt = "1.1.0"
compt = {path="../compt"}
axgeom = "1.0.0"
smallvec = "0.6.1"
dinotree_inner = {path="../dinotree_inner"}