[package]
name = "dinotree"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]


[dev-dependencies]
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
num = "0.1.42"
piston_window = "*"

[dependencies]
rayon = "1.0.1"
compt = {git ="https://github.com/tiby312/compt.git"}
axgeom = {git="https://github.com/tiby312/axgeom.git"}
smallvec = "0.6.1"
dinotree_inner = {git="https://github.com/tiby312/dinotree_inner.git"}