[package]
name = "dinotree_alg"
version = "0.1.1"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Dinotree algorithms"
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/dinotree_alg"
keywords = ["tree", "kdtree","dinotree","space-partitioning"]
readme = "readme.md"
edition = "2018"


[dev-dependencies]
rustc-test = "0.3.0"
dists = "0.1.0"

[dependencies]
is_sorted = "0.1.0"
rayon = "1.0.3"
smallvec = "0.6.5"
itertools = "0.7.8"
compt="1.4.0"
axgeom="1.0.5"
dinotree = {path="../dinotree"}
