[package]
name = "dinotree"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]


[dev-dependencies]
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
num = "0.1.42"


[dependencies]
ordered-float = "0.5.0"
rayon = "0.9.*"
pdqselect = "0.1.0"
odds = "0.2.25"  #used for Vec::retain_mut
compt = {path="../compt"}
axgeom = {path="../axgeom"}
smallvec = "0.6.0"
dinotree_inner = {path="../dinotree_inner"}