[package]
name = "dinotree_alg"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Dinotree algorithms"
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/dinotree_alg"
keywords = ["tree", "kdtree","dinotree","space-partitioning"]
readme = "readme.md"


[dev-dependencies]
rustc-test = "0.3.0"
dists = {path="dists"}

[dependencies]
is_sorted = "0.1.0"
rayon = "1.0.2"
smallvec = "0.6.1"
compt = "1.2.2"
axgeom = "1.0.1"
dinotree = "0.1.1"