[package]
name = "dinotree_alg"
version = "0.4.1"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Dinotree algorithms"
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/dinotree_alg"
keywords = ["tree", "kdtree","dinotree","space-partitioning"]
readme = "readme.md"
edition = "2018"


[dev-dependencies]
dists = "*"


[dependencies]
is_sorted = "0.1"
itertools = "0.8"
dinotree ="0.5"
rayon = "1.2"