[package]
name = "dinotree_alg"
version = "0.2.2"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Dinotree algorithms"
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/dinotree_alg"
keywords = ["tree", "kdtree","dinotree","space-partitioning"]
readme = "readme.md"
edition = "2018"


[dev-dependencies]
rustc-test = "0.3.0"
dinotree_sample={path="../dinotree_sample"}

[dependencies]
is_sorted = "0.1.1"
rayon = "1.1.0"
smallvec = "0.6.10"
itertools = "0.7.8"
#compt="1.5.6"
compt = {path = "../compt"}
axgeom = {path="../axgeom"}
dinotree ={path="../dinotree"}

[features]
#unstable =[]