[package]
name = "dinotree_alg"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]


[dev-dependencies]
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
num = "0.1.42"
piston_window = "*"

[dependencies]
is_sorted = "0.1.0"
rayon = "1.0.2"
smallvec = "0.6.1"
compt = "1.2.2"
axgeom = "1.0.1"
dinotree = "0.1.0"