[package]
name = "dinotree_alg"
version = "0.1.1"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Dinotree algorithms"
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/dinotree_alg"
keywords = ["tree", "kdtree","dinotree","space-partitioning"]
readme = "readme.md"


[dev-dependencies]
rustc-test = "0.3.0"
dists = "0.1.0"

[dependencies]
is_sorted = "0.1.0"
rayon = "1.0.3"
smallvec = "0.6.5"
itertools = "0.7.8"
compt = "1.2.5"
axgeom = "1.0.4"
#dinotree = "0.1.3"
dinotree = {path="../dinotree"}
