[package]
name = "dinotree_alg_data"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
dinotree_alg = {path=".."}
dists = "0.1.6"
gnuplot = "0.0.27"
duckduckgeo = "0.2.2"
dinotree = "0.4.4"
num_cpus = "1.10.1"

#[profile.release]
#opt-level = 2
