[package]
name = "dinotree_alg_data"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
num-traits = "0.2"
dists="0.1.3"
gnuplot = "0.0.26"
rayon="1.0.3"
smallvec = "0.6.5"
duckduckgeo = "0.2.0"
dinotree_alg = {path=".."}
new-ordered-float = "1.0.1"
rustc-test = "0.3.0"
compt = "1.4.0"
axgeom = "1.0.5"
dinotree = "0.2.1"
