[package]
name = "dinotree_alg_data"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
dinotree_alg = {path=".."}
dists = "*"
gnuplot = "*"
duckduckgeo = "*"
dinotree = {path="../../dinotree"}
rayon = "1.2"
num_cpus = "*"
