[package]
name = "dinotree_alg_data"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
dinotree_alg = {path=".."}
dists = "0.2"
gnuplot = "*"
duckduckgeo = "0.2"
dinotree = "0.5"
rayon = "1.2"
num_cpus = "*"
