[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
dists={path="../../dists"}
dinotree={path="../../dinotree"}
duckduckgeo = {path="../../duckduckgeo"}#"0.2.1"
dinotree_alg = {path=".."}
piston_window = "0.103.0"
bit-vec = "0.6.1"
