[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
num-traits = "0.2"
compt = "1.4.0"
axgeom = "1.0.5"
dinotree = "0.2.1"
duckduckgeo = "0.2.1"
dinotree_alg = {path=".."}
new-ordered-float = "1.0.1"
rand = "0.3"
rustc-test = "0.3.0"
piston_window = "0.84.0"