[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
csv="*"
rayon="*"
compt = {git ="https://github.com/tiby312/compt.git"}
axgeom = {git="https://github.com/tiby312/axgeom.git"}
smallvec = "0.6.1"
dinotree_inner = {path="../../dinotree_inner"}

dinotree_geom={git="https://github.com/tiby312/dinotree_geom"}
dinotree = {path=".."}
new-ordered-float = "1.0.1"
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
piston_window = "*"