[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]

[dependencies]
rayon="*"
compt={path="../../compt"}
dinotree_geom={path="../../dinotree_geom"}
dinotree = {path=".."}
dinotree_inner = {path="../../dinotree_inner"}
axgeom={path="../../axgeom"}
new-ordered-float = "1.0.1"
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
piston_window = "*"