[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]

[dependencies]
compt={path="../../compt"}
dinotree = {path=".."}
dinotree_inner = {path="../../dinotree_inner"}
axgeom={path="../../axgeom"}
ordered-float = "0.5.0"
rand = "0.3"
rustc-test = "0.3.0"
collision = "0.15.0"
cgmath = "0.16.0"
num = "0.1.42"
piston_window = "*"