[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
dists= "0.2"
dinotree="0.5"
duckduckgeo = "0.2"
dinotree_alg = {path=".."}
piston_window = "0.103.0"
bit-vec = "0.6"
num_cpus = "1.10"
rayon = "1.2"
