[package]
name = "dinotree_alg_demo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
num-traits = "0.2"
#compt = "1.4.0"
compt = {path = "../../compt"}
#axgeom = "1.0.5"
axgeom = {path="../../axgeom"}
dists={path="../../dists"}
#dinotree = "0.2.1"
dinotree={path="../../dinotree"}
duckduckgeo = {path="../../duckduckgeo"}#"0.2.1"
dinotree_alg = {path=".."}
ordered-float = "1.0.2"
rustc-test = "0.3.0"
piston_window = "0.103.0"
cgmath = "0.17.0"
bit-vec = "0.6.1"